rolled back rebranding change

diff --git a/build-a-pi b/build-a-pi
--- a/build-a-pi
+++ b/build-a-pi
@@ -82,7 +82,7 @@ Build a Pi 3.2.0 and later does not support
 RaspiOS Buster or earlier versions of RaspiOS.
 You should consider upgrading to RaspiOS 11
 (Bullseye). By clicking ok you will be moved
-to the last version of CQ Linux (1.0.0) that 
+to the last version of CQ Linux (3.1.4) that 
 supports Pi OS Buster. Please note there are 
 no plans to update Build a Pi for Buster going 
 forward.  In other words, you are on your own 
@@ -103,9 +103,9 @@ INTRO=$(yad --width=600 --height=300 --text-align=center --center --title="Out o
 	exit
 	fi
 	rm ${NOTICEPATH}/intro.txt
-	cd $HOME/CQ-Linux
+	cd $HOME/pi-build
 	git checkout buster 
-	bash CQ-Linux & exit
+	bash build-a-pi & exit
 fi
 
 #####################################
@@ -163,7 +163,7 @@ if you choose to install everything. If you find it
 helpful please consider a donation to encourage future
 development.
 
-https://paypal.me/cqLinux
+https://paypal.me/km4ack
 EOF
 
 INTRO=$(yad --width=550 --height=250 --text-align=center --center --title="CQ-Linux" --show-uri \
@@ -509,7 +509,7 @@ sudo sed -i 's/#hdmi_force_hotplug=1/hdmi_force_hotplug=1/' config.txt
 
 #set wallpaper
 #fix issue 193
-sudo cp $HOME/CQ-Linux/bap-wallpaper.jpg /usr/share/rpd-wallpaper/
+sudo cp $HOME/pi-build/bap-wallpaper.jpg /usr/share/rpd-wallpaper/
 pcmanfm --set-wallpaper /usr/share/rpd-wallpaper/bap-wallpaper.jpg
 
 mkdir -p ${DIR} 2>/dev/null
@@ -548,15 +548,15 @@ mkdir -p ${HOME}/bin
 echo "export PATH=$PATH:${HOME}/bin" >>${HOME}/.bashrc
 
 #set update script to exec
-chmod +x ${MYPATH}/update ${MYPATH}/CQ-Linux
+chmod +x ${MYPATH}/update ${MYPATH}/build-a-pi
 
-#create CQ-Linux menu item
+#create build-a-pi menu item
 cd ${MYPATH} || ! echo "Failure"
-cat >cq-linux.desktop <<EOF
+cat >build-a-pi.desktop <<EOF
 [Desktop Entry]
-Name=cq-linux
-GenericName=cq-linux
-Comment=cq-linux App Manager
+Name=Build-a-Pi
+GenericName=KM4ACK Build-a-Pi
+Comment=Build-a-Pi App Manager
 Exec=${MYPATH}/update
 Icon=${MYPATH}/logo.png
 Terminal=true
@@ -564,19 +564,19 @@ Type=Application
 Categories=Settings;DesktopSettings;GTK;X-LXDE-Settings;
 EOF
 
-sudo mv cq-linux.desktop /usr/share/applications/
+sudo mv build-a-pi.desktop /usr/share/applications/
 
 #create repair-bap tool
 cat <<EOF > /run/user/$UID/repair-bap
 #!/bin/bash
 
-if [ ! -f $HOME/CQ-Linux/update ]; then
+if [ ! -f $HOME/pi-build/update ]; then
 echo "################################"
 echo "#  BAP update tool not found.  #"
 echo "#  Repairing, please stand by  #"
 echo "################################"
 cd $HOME
-git clone https://github.com/CQ-Linux/CQ-Linux.git || echo "Could not connect to Github. Check your internet and try again"
+git clone https://github.com/bwattendorf/pi-build_x86.git || echo "Could not connect to Github. Check your internet and try again"
 echo "Repair complete. Run the Build a Pi update tool using the shortcut in the Pi menu"
 else
 clear;echo;echo
@@ -633,7 +633,7 @@ done <${UTILITY}
 
 #create new menu subcategories. One for FLDIGI Suite and
 #one for Build a Pi.
-bash ${HOME}/CQ-Linux/menu-update
+bash ${HOME}/pi-build/menu-update
 
 
 
diff --git a/update b/update
--- a/update
+++ b/update
@@ -79,9 +79,9 @@ INTRO=$(yad --width=600 --height=300 --text-align=center --center --title="Out o
 	exit
 	fi
 	rm ${NOTICEPATH}/intro.txt
-	cd $HOME/CQ-Linux
+	cd $HOME/pi-build
 	git checkout buster 
-	bash CQ-Linux & exit
+	bash build-a-pi & exit
 fi
 
 #####################################
@@ -91,8 +91,8 @@ fi
 #remove temp dir if exist
 #fix issue 108 https://github.com/km4ack/pi-build/issues/108
 #Thanks to N5RKS for finding the bug
-if [ -d ${HOME}/CQ-Linux/temp ]; then
-	rm -rf "${HOME}/CQ-Linux/temp"
+if [ -d ${HOME}/pi-build/temp ]; then
+	rm -rf "${HOME}/pi-build/temp"
 fi
 
 #####################################
@@ -106,17 +106,17 @@ mkdir -p ${HOME}/.config/autostart
 echo "Checking for Build a Pi updates"
 CURRENT=$(head -1 ${MYPATH}/changelog | sed s'/version=//')
 
-LATEST=$(curl -s https://raw.githubusercontent.com/CQ-Linux/CQ-Linux/main/changelog | tac | tac | head -1 | sed 's/version=//')
+LATEST=$(curl -s https://raw.githubusercontent.com/bwattendorf/pi-build_x86/dev/changelog | tac | tac | head -1 | sed 's/version=//')
 
 if (($(echo "$LATEST $CURRENT" | awk '{print ($1 > $2)}'))); then
 	cat <<EOF >${MYPATH}/updatebap.txt
 Build a Pi update available. Current version is $CURRENT and
 the lateest version is $LATEST. Would you like to update?
 
-Change log - https://github.com/CQ-Linux/CQ-Linux/blob/main/changelog
+Change log - https://github.com/km4ack/pi-build/blob/master/changelog
 EOF
 	BAP=$(
-		yad --width=650 --height=250 --text-align=center --center --title="CQ-Linux" --show-uri \
+		yad --width=650 --height=250 --text-align=center --center --title="Build-a-Pi" --show-uri \
 			--image ${LOGO} --window-icon=${LOGO} --image-on-top --separator="|" --item-separator="|" \
 			--text-info \
 			--button="Yes":2 \
@@ -138,7 +138,7 @@ EOF
 		mv ${MYPATH}/config ${HOME}/Documents/config.bap
 		rm -rf "${MYPATH}"
 		cd ~ || ! echo "Failure"
-		git clone --branch main https://github.com/CQ-Linux/CQ-Linux.git /${HOME}/CQ-Linux
+		git clone --branch dev https://github.com/bwattendorf/pi-build_x86.git /${HOME}/pi-build
 		mv ${HOME}/Documents/config.bap ${MYPATH}/config 
 
 		cat <<EOF >${MYPATH}/updatebap.txt
@@ -168,7 +168,7 @@ clear
 #been applied previously. If so, it skips the patch screen. If not, it gives
 #the user an option to install the patch(es).
 
-PATCHCHECK=$(curl -s https://raw.githubusercontent.com/CQ-Linux/CQ-Linux/main/patch/README.md | grep PATCH= | sed 's/PATCH=//')
+PATCHCHECK=$(curl -s https://raw.githubusercontent.com/km4ack/pi-build/dev/patch/README.md | grep PATCH= | sed 's/PATCH=//')
 
 if [ ${PATCHCHECK} = "YES" ]; then
 #Setup temp directory for BAP patches and download patches
@@ -176,19 +176,19 @@ echo "##########################################################"
 echo "#Checking for available patches that haven't been applied#"
 echo "##########################################################"
 cd /run/user/$UID
-git init CQ-Linux
-cd CQ-Linux
-git remote add -f origin https://github.com/CQ-Linux/CQ-Linux.git
+git init pi-build
+cd pi-build
+git remote add -f origin https://github.com/km4ack/pi-build.git
 git config core.sparseCheckout true
 echo "/patch" >> .git/info/sparse-checkout
-git pull origin main
+git pull origin dev
 
-FILES=$(ls -I README.md /run/user/$UID/CQ-Linux/patch)
+FILES=$(ls -I README.md /run/user/$UID/pi-build/patch)
 
 #check if available patches have already been applied to BAP
 for i in $FILES; do
 
-NAME=$(grep PATCHNAME= /run/user/$UID/CQ-Linux/patch/$i | sed 's/PATCHNAME=//')
+NAME=$(grep PATCHNAME= /run/user/$UID/pi-build/patch/$i | sed 's/PATCHNAME=//')
 RB=$(grep $NAME $HOME/.config/patch)
 if [ -z $RB ]; then
 echo "$NAME" >> /run/user/$UID/avail-patch.txt
@@ -203,14 +203,14 @@ cat <<EOF >${MYPATH}/patch.txt
 One or more patch scripts are currently
 available for Build a Pi. Full description
 of each available patch can be found at
-https://github.com/CQ-Linux/CQ-Linux/tree/dev/patch
+https://github.com/km4ack/pi-build/tree/dev/patch
 
 Would you like to review/apply 
 available patch scripts?
 EOF
 
-INTRO=$(yad --width=650 --height=300 --text-align=center --center --title="CQ-Linux Patch Tool" --show-uri \
-	--image ${LOGO} --window-icon=${LOGO} --image-on-top --separator="|" --item-separator="|" --text="CQ-Linux Patch Tool" \
+INTRO=$(yad --width=650 --height=300 --text-align=center --center --title="Build-a-Pi Patch Tool" --show-uri \
+	--image ${LOGO} --window-icon=${LOGO} --image-on-top --separator="|" --item-separator="|" --text="Build-a-Pi Patch Tool" \
 	--text-info \
 	--button="Yes":1 \
 	--button="No":2 <${MYPATH}/patch.txt \
@@ -220,20 +220,20 @@ BUT=$?
 		if [ ${BUT} = 252 ]; then
 		echo "Button ${BUT} pressed"
 		rm ${MYPATH}/patch.txt
-		rm -rf /run/user/$UID/CQ-Linux
+		rm -rf /run/user/$UID/pi-build
 		exit
 		elif [ ${BUT} = 1 ]; then
 		echo "Button ${BUT} pressed"
 		rm ${MYPATH}/patch.txt
-		lxterminal -e bash $HOME/CQ-Linux/patch-menu && exit
+		lxterminal -e bash $HOME/pi-build/patch-menu && exit
 		elif [ ${BUT} = 2 ]; then
 		echo "Button ${BUT} pressed"
 		rm ${MYPATH}/patch.txt
 		echo "user declined patch updates continuing with Build a Pi update"
-		rm -rf /run/user/$UID/CQ-Linux
+		rm -rf /run/user/$UID/pi-build
 		fi
 	else
-	rm -rf /run/user/$UID/CQ-Linux	
+	rm -rf /run/user/$UID/pi-build	
 	fi
 fi
 
@@ -338,7 +338,7 @@ if [ -n "$HS" ]; then
 			--text="<b>HotSpot Information\r\rPlease enter the information\rbelow \
 for the Hot Spot\r</b>NOTE: The last field is the password for the hotspot. You will use this password to \
 connect to your Pi when it is in hotspot mode <b>This password can only contain letters and numbers</b>" \
-			--title="CQ-Linux" \
+			--title="Build-a-Pi" \
 			--field="Home Wifi SSID":CB "${LIST}" \
 			--field="Home Wifi Password" \
 			--field="Hot Spot Password" \
@@ -370,7 +370,7 @@ if [ -n "$HS" ]; then
 		yad --center --form --width=300 --height=200 --separator="|" \
 			--image ${LOGO} --column=Check --column=App --column=Description \
 			--window-icon=${LOGO} --image-on-top --text-align=center \
-			--text="<b>Hotspot password has to be 8-63 characters</b>" --title="CQ-Linux" \
+			--text="<b>Hotspot password has to be 8-63 characters</b>" --title="Build-a-Pi" \
 			--button=gtk-ok
 		HSINFO
 	fi
@@ -566,13 +566,13 @@ if [ ! -f /usr/local/bin/repair-bap ]; then
 cat <<EOF > /run/user/$UID/repair-bap
 #!/bin/bash
 
-if [ ! -f $HOME/CQ-Linux/update ]; then
+if [ ! -f $HOME/pi-build/update ]; then
 echo "################################"
 echo "#  BAP update tool not found.  #"
 echo "#  Repairing, please stand by  #"
 echo "################################"
 cd $HOME
-git clone https://github.com/CQ-Linux/CQ-Linux.git || echo "Could not connect to Github. Check your internet and try again"
+git clone https://github.com/km4ack/pi-build.git || echo "Could not connect to Github. Check your internet and try again"
 echo "Repair complete. Run the Build a Pi update tool using the shortcut in the Pi menu"
 else
 clear;echo;echo
@@ -633,7 +633,7 @@ done <${UTILITY}
 
 #create new menu subcategories. One for FLDIGI Suite and
 #one for Build a Pi.
-bash ${HOME}/CQ-Linux/menu-update
+bash ${HOME}/pi-build/menu-update
 
 #####################################
 #	END CLEANUP
