getting ready for release

diff --git a/build-a-pi b/build-a-pi
--- a/build-a-pi
+++ b/build-a-pi
@@ -78,13 +78,13 @@ if [ "$V_ID" -le 10 ]; then
 NOTICEPATH=/run/user/$UID
 
 cat <<EOF >${NOTICEPATH}/intro.txt
-Build a Pi 3.2.0 and later does not support
+CQ-Linux 0.1.0 and later does not support
 RaspiOS Buster or earlier versions of RaspiOS.
 You should consider upgrading to RaspiOS 11
 (Bullseye). By clicking ok you will be moved
-to the last version of CQ Linux (3.1.4) that 
+to the last version of CQ Linux (1.0.0) that 
 supports Pi OS Buster. Please note there are 
-no plans to update Build a Pi for Buster going 
+no plans to update CQ-Linux for Buster going 
 forward.  In other words, you are on your own 
 if it is broke and you are still running Pi OS
 10 (Buster).
@@ -163,7 +163,7 @@ if you choose to install everything. If you find it
 helpful please consider a donation to encourage future
 development.
 
-https://paypal.me/km4ack
+https://paypal.me/cqLinux
 EOF
 
 INTRO=$(yad --width=550 --height=250 --text-align=center --center --title="CQ-Linux" --show-uri \
@@ -408,7 +408,6 @@ yad --center --list --checklist --width=600 --height=600 --separator="" \
 	false "GRIDCALC" "Grid Calculation Software" \
 	false "ECHOLINK" "Digital audio mode" \
 	false "REPEAT" "Repeater Directory" \
-	false "DIGIPI" "DIGI-PI integration" \
 	false "CLOUDLOG" "Web Based Logging Software" \
 	false "QDMR" "DRM programmer" \
 	--button="Exit":1 \
@@ -422,7 +421,7 @@ fi
 if [ ${BUT} = 3 ]; then
 	ADDAPPS=(CONKY PI-APRS CHIRP GARIM PAT PAT-MENU JS8CALL M0IAX WSJTX PYQSO
 		HAMRS EES QSSTV GRIDTRACKER HAMCLOCK PROPAGATION YAAC XASTIR GPREDICT TQSL
-		GRIDCALC ECHOLINK CQRLOG DIGIPI CLOUDLOG REPEAT QDMR)
+		GRIDCALC ECHOLINK CQRLOG CLOUDLOG REPEAT QDMR)
 
 	for i in "${ADDAPPS[@]}"; do
 		echo "$i" >>${ADDITIONAL}
@@ -501,8 +500,8 @@ crontab -l >$TEMPCRON
 echo "@reboot sleep 10 && export DISPLAY=:0 && ${MYPATH}/.complete" >>$TEMPCRON
 ${MYPATH}/.funfacts &
 #upgrade the system
-sudo apt-get -y upgrade
-sudo apt -y full-upgrade
+#sudo apt-get -y upgrade
+#sudo apt -y full-upgrade
 
 #fix issue 254 05JULY2021
 sudo sed -i 's/#hdmi_force_hotplug=1/hdmi_force_hotplug=1/' config.txt
@@ -576,7 +575,7 @@ echo "#  BAP update tool not found.  #"
 echo "#  Repairing, please stand by  #"
 echo "################################"
 cd $HOME
-git clone https://github.com/bwattendorf/pi-build_x86.git || echo "Could not connect to Github. Check your internet and try again"
+git clone https://github.com/CQ-Linux/CQ-Linux.git || echo "Could not connect to Github. Check your internet and try again"
 echo "Repair complete. Run the Build a Pi update tool using the shortcut in the Pi menu"
 else
 clear;echo;echo
diff --git a/update b/update
--- a/update
+++ b/update
@@ -106,14 +106,14 @@ mkdir -p ${HOME}/.config/autostart
 echo "Checking for Build a Pi updates"
 CURRENT=$(head -1 ${MYPATH}/changelog | sed s'/version=//')
 
-LATEST=$(curl -s https://raw.githubusercontent.com/bwattendorf/pi-build_x86/dev/changelog | tac | tac | head -1 | sed 's/version=//')
+LATEST=$(curl -s https://raw.githubusercontent.com/CQ-Linux/CQ-Linux/main/changelog | tac | tac | head -1 | sed 's/version=//')
 
 if (($(echo "$LATEST $CURRENT" | awk '{print ($1 > $2)}'))); then
 	cat <<EOF >${MYPATH}/updatebap.txt
 Build a Pi update available. Current version is $CURRENT and
 the lateest version is $LATEST. Would you like to update?
 
-Change log - https://github.com/km4ack/pi-build/blob/master/changelog
+Change log - https://github.com/CQ-Linux/CQ-Linux/blob/main/changelog
 EOF
 	BAP=$(
 		yad --width=650 --height=250 --text-align=center --center --title="Build-a-Pi" --show-uri \
@@ -138,7 +138,7 @@ EOF
 		mv ${MYPATH}/config ${HOME}/Documents/config.bap
 		rm -rf "${MYPATH}"
 		cd ~ || ! echo "Failure"
-		git clone --branch dev https://github.com/bwattendorf/pi-build_x86.git /${HOME}/pi-build
+		git clone --branch main https://github.com/CQ-Linux/CQ-Linux.git /${HOME}/pi-build
 		mv ${HOME}/Documents/config.bap ${MYPATH}/config 
 
 		cat <<EOF >${MYPATH}/updatebap.txt
@@ -178,7 +178,7 @@ echo "##########################################################"
 cd /run/user/$UID
 git init pi-build
 cd pi-build
-git remote add -f origin https://github.com/km4ack/pi-build.git
+git remote add -f origin https://github.com/CQ-Linux/CQ-Linux.git
 git config core.sparseCheckout true
 echo "/patch" >> .git/info/sparse-checkout
 git pull origin dev
@@ -201,16 +201,16 @@ done
 
 cat <<EOF >${MYPATH}/patch.txt
 One or more patch scripts are currently
-available for Build a Pi. Full description
+available for CQ-Linux. Full description
 of each available patch can be found at
-https://github.com/km4ack/pi-build/tree/dev/patch
+https://github.com/CQ-Linux/CQ-Linux/tree/main/patch
 
 Would you like to review/apply 
 available patch scripts?
 EOF
 
-INTRO=$(yad --width=650 --height=300 --text-align=center --center --title="Build-a-Pi Patch Tool" --show-uri \
-	--image ${LOGO} --window-icon=${LOGO} --image-on-top --separator="|" --item-separator="|" --text="Build-a-Pi Patch Tool" \
+INTRO=$(yad --width=650 --height=300 --text-align=center --center --title="CQ-Linux Patch Tool" --show-uri \
+	--image ${LOGO} --window-icon=${LOGO} --image-on-top --separator="|" --item-separator="|" --text="CQ-Linux Patch Tool" \
 	--text-info \
 	--button="Yes":1 \
 	--button="No":2 <${MYPATH}/patch.txt \
@@ -229,7 +229,7 @@ BUT=$?
 		elif [ ${BUT} = 2 ]; then
 		echo "Button ${BUT} pressed"
 		rm ${MYPATH}/patch.txt
-		echo "user declined patch updates continuing with Build a Pi update"
+		echo "user declined patch updates continuing with CQ-Linux update"
 		rm -rf /run/user/$UID/pi-build
 		fi
 	else
@@ -338,7 +338,7 @@ if [ -n "$HS" ]; then
 			--text="<b>HotSpot Information\r\rPlease enter the information\rbelow \
 for the Hot Spot\r</b>NOTE: The last field is the password for the hotspot. You will use this password to \
 connect to your Pi when it is in hotspot mode <b>This password can only contain letters and numbers</b>" \
-			--title="Build-a-Pi" \
+			--title="CQ-Linux" \
 			--field="Home Wifi SSID":CB "${LIST}" \
 			--field="Home Wifi Password" \
 			--field="Hot Spot Password" \
@@ -370,7 +370,7 @@ if [ -n "$HS" ]; then
 		yad --center --form --width=300 --height=200 --separator="|" \
 			--image ${LOGO} --column=Check --column=App --column=Description \
 			--window-icon=${LOGO} --image-on-top --text-align=center \
-			--text="<b>Hotspot password has to be 8-63 characters</b>" --title="Build-a-Pi" \
+			--text="<b>Hotspot password has to be 8-63 characters</b>" --title="CQ-Linux" \
 			--button=gtk-ok
 		HSINFO
 	fi
@@ -467,7 +467,6 @@ yad --center --list --checklist --width=600 --height=600 --separator="" \
 	false "TQSL" "$TQSL" "LOTW Software" \
 	false "GRIDCALC" "$GRIDCALC" "Grid Calculation Software" \
 	false "ECHOLINK" "$ECHOLINK" "Digital audio mode" \
-	false "DIGIPI" "$DIGIPI" "DIGIPI integration" \
 	false "CLOUDLOG" "$CLOUDLOG" "web based Logging Software" \
 	false "QDMR" "$QDMR" "DMR radio programmer" \
 	--button="Exit":1 \
@@ -572,7 +571,7 @@ echo "#  BAP update tool not found.  #"
 echo "#  Repairing, please stand by  #"
 echo "################################"
 cd $HOME
-git clone https://github.com/km4ack/pi-build.git || echo "Could not connect to Github. Check your internet and try again"
+git clone https://github.com/CQ-Linux/CQ-Linux.git || echo "Could not connect to Github. Check your internet and try again"
 echo "Repair complete. Run the Build a Pi update tool using the shortcut in the Pi menu"
 else
 clear;echo;echo
